---

- name: "Create {{ bm_user }} user"
  user:
    name: "{{ bm_user }}"
    state: "present"
    shell: "/usr/sbin/nologin"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Configure s3cmd
  template:
    src: "s3cfg.j2"
    dest: "/home/{{ bm_user }}/.s3cfg"
    owner: "{{ bm_user }}"
    group: "{{ bm_user }}"
    mode: u=r,g=r,o=
  when: bm_upload_method == 's3'

- name: Render /etc/backup-manager.conf
  template:
    src: backup-manager.conf.j2
    dest: /etc/backup-manager.conf

- name: Render pre_backup.sh
  template:
    src: pre_backup.sh.j2
    dest: "/home/{{ bm_user }}/pre_backup.sh"
    owner: "{{ bm_user }}"
    group: "{{ bm_user }}"
    mode: u=rx,g=rx,o=

- name: Render post_backup.sh
  template:
    src: post_backup.sh.j2
    dest: "/home/{{ bm_user }}/post_backup.sh"
    owner: "{{ bm_user }}"
    group: "{{ bm_user }}"
    mode: u=rx,g=rx,o=

#HOME is unset to avoid using .my.cnf config : https://github.com/sukria/Backup-Manager/issues/12
- name: Creates cronjob to execute backup-manager
  cron:
    day: "{{ item.startday | default('*') }}"
    hour: "{{ item.starthour }}"
    minute: "{{ item.startmin | default('0') }}"
    name: "backup-manager_backup tag='{{ item.tag }}'"
    user: "root"
    job: "HOME='' /usr/sbin/backup-manager --verbose 2>&1 | logger -t {{ bm_bkpcron_rsyslog_progname }}"
  when: (item.disable is not defined or not item.disable) and item.tag is defined and item.starthour is defined
  with_items: "{{ bm_backup_schedule }}"

- name: Activate backup manager customs logs in syslog
  lineinfile:
    line: "if $programname == '{{ item }}' then /var/log/{{ item }}.log"
    regexp: "^if \\$programname"
    dest: "/etc/rsyslog.d/{{ item }}.conf"
    create: true
  with_items:
    - "{{ bm_bkpcron_rsyslog_progname }}"
  notify: rsyslog restart
